---
# tasks file for aws-corretto
#------------------------------------------------------
## Download and install AWS corretto 

- name: download tar from aws download
  get_url:
    url: "{{ corretto_base_url }}/{{ corretto_major_version }}.{{ corretto_minor_version }}/amazon-corretto-{{ corretto_major_version }}.{{ corretto_minor_version }}-{{ corretto_platform }}.tar.gz"
    dest: /tmp/
  when: "corretto_major_version > '8' and corretto_minor_version > '0'"

- name: create archive directory
  file:
    path: /opt/java
    state: directory
  
- name: extract archive to destination directory
  unarchive:
    src: /tmp/amazon-corretto-{{ corretto_major_version }}.{{ corretto_minor_version }}-{{ corretto_platform }}.tar.gz
    dest: /opt/java
    extra_opts: [--strip-components=1]
  
- name:  clean downloaded archive file
  file:
   path: /tmp/amazon-corretto-{{ corretto_major_version }}.{{ corretto_minor_version }}-{{ corretto_platform }}.tar.gz
   state: absent
  
## create symlinks for AWS Corretto
- name: create symlink for java
  alternatives:
    name: java
    path: /opt/java/bin/java
    link: /usr/bin/java
    priority: 100
  when: "corretto_major_version > '8' and corretto_minor_version > '0'"

- name: create symlink for javac
  alternatives:
    name: javac
    path: /opt/java/bin/javac
    link: /usr/bin/javac
    priority: 100
  when: "corretto_major_version > '8' and corretto_minor_version > '0'"